- TensorFlow/LanguageModeling/BERT/launcher.sh
- TensorFlow/LanguageModeling/BERT/modeling.py
- TensorFlow/LanguageModeling/BERT/optimization.py
- TensorFlow/LanguageModeling/BERT/requirements.sh
- TensorFlow/LanguageModeling/BERT/run_pretraining.py
- TensorFlow2/Segmentation/MaskRCNN/Dockerfile
- TensorFlow2/Segmentation/MaskRCNN/download_and_process_pretrained_weights.sh
- TensorFlow2/Segmentation/MaskRCNN/mask_rcnn/dataloader.py
- TensorFlow2/Segmentation/MaskRCNN/mask_rcnn/distributed_executer.py
- TensorFlow2/Segmentation/MaskRCNN/mask_rcnn/hooks/logging_hook.py
- TensorFlow2/Segmentation/MaskRCNN/mask_rcnn/mask_rcnn_model.py
- TensorFlow2/Segmentation/MaskRCNN/mask_rcnn/utils/distributed_utils.py
- TensorFlow2/Segmentation/MaskRCNN/mask_rcnn/utils/logging_backend.py
- TensorFlow2/Segmentation/MaskRCNN/mask_rcnn_main.py
- TensorFlow2/Segmentation/MaskRCNN/requirements.sh
- TensorFlow2/Segmentation/MaskRCNN/scripts/benchmark_training.py
- TensorFlow2/Segmentation/MaskRCNN/scripts/docker/launch_tf1.sh
- TensorFlow2/Segmentation/MaskRCNN/scripts/train_AMP_8GPU.sh
> TF MaskRCNN and TF BERT w/Herring

- TensorFlow/LanguageModeling/BERT/launcher.sh
- TensorFlow/LanguageModeling/BERT/optimization.py
- TensorFlow/LanguageModeling/BERT/run_pretraining.py
> Removed Horovod import and Fixed variable naming

- TensorFlow2/Segmentation/MaskRCNN/requirements.sh
After that TF Markrcnn will use 1.15 of TF
> Remove 1.14 special installation for TF

- PyTorch/Segmentation/MaskRCNN/pytorch/maskrcnn_benchmark/config/paths_catalog.py
- PyTorch/Segmentation/MaskRCNN/pytorch/maskrcnn_benchmark/data/build.py
- PyTorch/Segmentation/MaskRCNN/pytorch/train_net_herring.py
- PyTorch/Segmentation/MaskRCNN/requirements.sh
> Fix requirements.sh and added command line dataset path parameter

- PyTorch/Segmentation/MaskRCNN/pytorch/maskrcnn_benchmark/engine/trainer.py
> Added throughput calculation in terms of samples per second for PyTorch Mask RCNN script

- TensorFlow/Detection/SSD/requirements.sh
> Fixed TF 1.x SSD path

- PyTorch/Segmentation/MaskRCNN/pytorch/maskrcnn_benchmark/engine/trainer.py
- PyTorch/Segmentation/MaskRCNN/requirements.sh
1. Capture final loss
2. Update deps
> PyTorch Mask RCNN full run support

- PyTorch/Segmentation/MaskRCNN/requirements.sh
Didn't upload the up-to-date requirement file, fixing it now
> Fix missing items in maskrcnn dependency

- TensorFlow2/Segmentation/MaskRCNN/mask_rcnn/distributed_executer.py
- TensorFlow2/Segmentation/MaskRCNN/mask_rcnn_main.py
> Fix for failing MaskRCNN

- TensorFlow/Classification/ConvNets/export_frozen_graph.py
- TensorFlow/Classification/ConvNets/main.py
- TensorFlow/Classification/ConvNets/model/resnet.py
- TensorFlow/Classification/ConvNets/requirements.sh
- TensorFlow/Classification/ConvNets/runtime/runner.py
- TensorFlow/Classification/ConvNets/utils/dali_utils.py
- TensorFlow/Classification/ConvNets/utils/data_utils.py
- TensorFlow/Classification/ConvNets/utils/hooks/training_hooks.py
- TensorFlow/Classification/ConvNets/utils/hvd_utils.py
> Convert TF 1.x Resnext101 to herring compatible

- TensorFlow/Classification/ConvNets/runtime/runner.py
- TensorFlow/Detection/SSD/models/research/object_detection/model_lib.py
- TensorFlow/Detection/SSD/models/research/object_detection/model_main.py
- TensorFlow/LanguageModeling/BERT/run_pretraining.py
- TensorFlow2/Segmentation/MaskRCNN/mask_rcnn_main.py
> Fixed a seed value to reduce randomness for TF 1.x models

- PyTorch/Segmentation/MaskRCNN/pytorch/maskrcnn_benchmark/engine/inference.py
- PyTorch/Segmentation/MaskRCNN/pytorch/maskrcnn_benchmark/utils/comm.py
This reverts commit 170dee7655ac42e7748378b6684eb8180b99bfa4.
> Revert "Validation Path for PT MRCNN #24"

- PyTorch/Detection/SSD/main.py
- PyTorch/Detection/SSD/src/coco_pipeline.py
- PyTorch/Detection/SSD/src/data.py
- PyTorch/Detection/SSD/src/train.py
- PyTorch/LanguageModeling/BERT/run_pretraining.py
- PyTorch/LanguageModeling/BERT/utils.py
- PyTorch/Segmentation/MaskRCNN/pytorch/maskrcnn_benchmark/data/samplers/distributed.py
- PyTorch/Segmentation/MaskRCNN/pytorch/maskrcnn_benchmark/engine/trainer.py
- PyTorch/Segmentation/MaskRCNN/pytorch/train_net_herring.py
- TensorFlow/Classification/ConvNets/export_frozen_graph.py
- TensorFlow/Classification/ConvNets/main.py
- TensorFlow/Classification/ConvNets/model/resnet.py
- TensorFlow/Classification/ConvNets/runtime/runner.py
- TensorFlow/Classification/ConvNets/utils/dali_utils.py
- TensorFlow/Classification/ConvNets/utils/data_utils.py
- TensorFlow/Classification/ConvNets/utils/hvd_utils.py
- TensorFlow/Detection/SSD/models/research/object_detection/builders/dataset_builder.py
- TensorFlow/Detection/SSD/models/research/object_detection/builders/optimizer_builder.py
- TensorFlow/Detection/SSD/models/research/object_detection/model_lib.py
- TensorFlow/Detection/SSD/models/research/object_detection/model_main.py
- TensorFlow/LanguageModeling/BERT/modeling.py
- TensorFlow/LanguageModeling/BERT/run_pretraining.py
- TensorFlow2/Segmentation/MaskRCNN/mask_rcnn/distributed_executer.py
- TensorFlow2/Segmentation/MaskRCNN/mask_rcnn/models/heads.py
- TensorFlow2/Segmentation/MaskRCNN/mask_rcnn/models/resnet.py
- TensorFlow2/Segmentation/MaskRCNN/mask_rcnn/utils/distributed_utils.py
- Renamed import `herring` to `smdistributed.dataparallel`
> Rename import herring to smdistributed.dataparallel

- PyTorch/Detection/SSD/main.py
- PyTorch/LanguageModeling/BERT/run_pretraining.py
- PyTorch/Segmentation/MaskRCNN/pytorch/maskrcnn_benchmark/data/build.py
- PyTorch/Segmentation/MaskRCNN/pytorch/maskrcnn_benchmark/engine/trainer.py
- PyTorch/Segmentation/MaskRCNN/pytorch/train_net_herring.py
- TensorFlow2/Segmentation/MaskRCNN/mask_rcnn/hooks/logging_hook.py
- TensorFlow2/Segmentation/MaskRCNN/mask_rcnn/mask_rcnn_model.py
> (Part-2) Rename import herring to smdistributed.dataparallel

- TensorFlow2/Segmentation/MaskRCNN/mask_rcnn_main.py
- TensorFlow2/Segmentation/MaskRCNN/mask_rcnn_sm.py
- TensorFlow2/Segmentation/MaskRCNN/requirements.sh
> Added TF2 Mask RCNN changes for SageMaker

- TensorFlow2/Segmentation/MaskRCNN/mask_rcnn_main.py
> added tf 2.4 script changes to MaskRCNN

- TensorFlow2/Segmentation/MaskRCNN/mask_rcnn_main.py
> MaskRCNN Changes for TF 2.4

- PyTorch/Segmentation/MaskRCNN/requirements.sh
To save download time and log print
> Add model download to requirement.sh

- PyTorch/LanguageModeling/Transformer-XL/pytorch/train.py
- PyTorch/LanguageModeling/Transformer-XL/pytorch/utils/distributed.py
Adapted this older snapshot of Transformer-XL to use SMDDP for record-keeping purposes. This is not fully functional in that it will eventually hit a hang if you run it long enough regardless of the seed due to unused parameters during a certain batch. 
Small set of benchmarking number with this version of the model: https://quip-amazon.com/P48gAvtU8yMW/Transformer-XL#DDS9CAi1KIv
> PT Transformer-XL with SM DDP

- PyTorch/Detection/SSD/main.py
- PyTorch/Detection/SSD/src/coco_pipeline.py
- PyTorch/Detection/SSD/src/data.py
- PyTorch/LanguageModeling/BERT/run_pretraining.py
- PyTorch/Segmentation/MaskRCNN/pytorch/tools/train_net.py
Fix loss regression of using PyTorch's DDP class in smddpv1.4.0.
Now we use the same version as NCCL branch. (Apex DDP or PT DDP).
This will produce the same loss as NCCL branch
> update smddp to v1.4.0

- PyTorch/Segmentation/MaskRCNN/pytorch/maskrcnn_benchmark/utils/comm.py
Fix get local rank in recent PR #66
> fix nccl local rank

- PyTorch/Segmentation/MaskRCNN/pytorch/maskrcnn_benchmark/data/samplers/distributed.py
- PyTorch/Segmentation/MaskRCNN/pytorch/maskrcnn_benchmark/engine/trainer.py
- PyTorch/Segmentation/MaskRCNN/pytorch/maskrcnn_benchmark/utils/comm.py
trainer is still using old API and caused double init.
> fix maskrcnn init

- PyTorch/Segmentation/MaskRCNN/pytorch/maskrcnn_benchmark/csrc/cuda/ROIAlign_cuda.cu
- PyTorch/Segmentation/MaskRCNN/pytorch/maskrcnn_benchmark/csrc/cuda/ROIPool_cuda.cu
- PyTorch/Segmentation/MaskRCNN/pytorch/maskrcnn_benchmark/csrc/cuda/box_encode.cu
- PyTorch/Segmentation/MaskRCNN/pytorch/maskrcnn_benchmark/csrc/cuda/box_iou.cu
- PyTorch/Segmentation/MaskRCNN/pytorch/maskrcnn_benchmark/csrc/cuda/generate_mask_targets.cu
- PyTorch/Segmentation/MaskRCNN/pytorch/maskrcnn_benchmark/csrc/cuda/match_proposals.cu
- PyTorch/Segmentation/MaskRCNN/pytorch/maskrcnn_benchmark/csrc/cuda/nms.cu
- PyTorch/Segmentation/MaskRCNN/pytorch/maskrcnn_benchmark/csrc/cuda/rpn_generate_proposals.cu
- PyTorch/Segmentation/MaskRCNN/pytorch/maskrcnn_benchmark/csrc/cuda/rpn_generate_proposals.h
> Fix for the NCCL maskrcnn Benchmark 
